### PR TITLE
Different style changes. Use grid system.

### PR DESCRIPTION
**Pull request by halfnibble**

### CODE REVIEW

**Comment by halfnibble** [comment]
There is a comment in the gallery template with an assignment for redoing that HTML. Use the first image as an example. Note: I renamed the templates to make sense. Please try to use meaningful names for templates.

To update your package versions, make sure the correct virtual environment is active, then type:
$ `pip install -r requirements.txt`

**Comment by halfnibble** [comment]
I forgot to add the gallery.html template. Here it is.

**Comment by RocketBrain** [comment]
Ok I am going to pull it right now.

How did you end up renaming the templates inside of the settings.py file? I
was trying to do that but kept getting an error loading the page whenever I
renamed the templates.

**Comment by halfnibble** [comment]
Create a new file in the templates dir. For example: "about_us.html". Then, inside of `mysite/settings.py` look for the `CMS_TEMPLATES` variable, and set it as follows: 

``` python
CMS_TEMPLATES = (
    ## Customize this
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
    ('menu_page.html', 'Menu Page'),
    ('about_us.html', 'About Us Page'),
)
```

For content to place inside of "about_us.html", try copying in the basic template from "page.html".

**Pull request merged**
